[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[selection]
save_to_clipboard = true

[window]
decorations = "None"
startup_mode = "Maximized"
# This setting makes your Option/Alt key act as the Meta key (sending Esc prefixes).
# This replaces the need for the long list of manual key bindings you had previously.
option_as_alt = "Both"

[font]
size = 18.0

[font.normal]
family = "Hack Nerd Font Mono"
# family = "Fira Code"
# family = "Source Code Pro"
# style = "Retina"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

# -----------------------------------------------------------------------------
# Key Bindings
# -----------------------------------------------------------------------------

# Ctrl + Space -> Null Byte
[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"

# Ctrl + V -> Paste
[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

# -----------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# Theme: Tokyo Night Storm
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_storm.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#24283b'
foreground = '#c0caf5'

# Normal colors
[colors.normal]
black = '#1d202f'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#ff899d'
green = '#9fe044'
yellow = '#faba4a'
blue = '#8db0ff'
magenta = '#c7a9ff'
cyan = '#a4daff'
white = '#c0caf5'

# # -----------------------------------------------------------------------------
# # TokyoNight Alacritty Colors
# # Theme: Tokyo Night Day
# # Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_day.toml
# # -----------------------------------------------------------------------------
#
# # Default colors
# [colors.primary]
# background = '#e1e2e7'
# foreground = '#3760bf'
#
# # Normal colors
# [colors.normal]
# black = '#b4b5b9'
# red = '#f52a65'
# green = '#587539'
# yellow = '#8c6c3e'
# blue = '#2e7de9'
# magenta = '#9854f1'
# cyan = '#007197'
# white = '#6172b0'
#
# # Bright colors
# [colors.bright]
# black = '#a1a6c5'
# red = '#ff4774'
# green = '#5c8524'
# yellow = '#a27629'
# blue = '#358aff'
# magenta = '#a463ff'
# cyan = '#007ea8'
# white = '#3760bf'
