[tools]
bat = "latest"
deno = "latest"
fd = "latest"
fx = "latest"
fzf = "latest"
jc = "latest"
jq = "latest"
neovim = "0.11.5"
node = "latest"
rg = "latest"
rust = "latest"
"ubi:ayoisaiah/f2" = "latest"
"ubi:gokcehan/lf" = "latest"
"ubi:jirutka/tty-copy" = "latest"
usage = "latest"
yq = "latest"
