[tools]
"asdf:neovim" = "ref:v0.11.5"
bat = "latest"
coreutils = "latest"
deno = "latest"
fd = "latest"
fx = "latest"
fzf = "latest"
"github:fish-shell/fish-shell" = "latest"
jc = "latest"
jq = "latest"
lua = "5.1"
markdownlint-cli2 = "latest"
node = "latest"
rg = "latest"
rust = "latest"
tree-sitter = "latest"
"ubi:ayoisaiah/f2" = "latest"
"ubi:gokcehan/lf" = "latest"
"ubi:jirutka/tty-copy" = "latest"
"ubi:shenwei356/rush" = "latest"
usage = "latest"
viddy = "latest"
watchexec = "latest"
yq = "latest"
